name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: thesis.pdf
          path: main.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0-${{ github.run_number }}
          release_name: Automated build ${{ github.run_number }}
          draft: false
          prerelease: true
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
